### ISSUE TITLE
Программа не может нормально принимать стандартный путь стим с пробелами

### ISSUE THREAD

**Issue by FelixANTI** [EvrkMs/AutoUpdateSteamGames#1]
Стандартный путь к клиенту стима такой:
C:\Program Files (x86)\Steam

При попытке прописать этот путь в программе clientpath "C:\Program Files (x86)\Steam" программа записывает путь как "C:\Program"(это видно в конфиге) игнорируя любые пробелы, что приводит к невозможности пользоваться программой дальше.
Исправь, пожалуйста.

**Comment by EvrkMs** [comment]
> Стандартный путь к клиенту стима такой: C:\Program Files (x86)\Steam
> 
> При попытке прописать этот путь в программе clientpath "C:\Program Files (x86)\Steam" программа записывает путь как "C:\Program"(это видно в конфиге) игнорируя любые пробелы, что приводит к невозможности пользоваться программой дальше. Исправь, пожалуйста.

В версии v1.1.7 которую только что выпустил пофиксил данную проблему
Спасибо вам
